// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm_KRxWj9GWn1VOedK0YKUWY6FXb37YdA',
    appId: '1:816730900420:web:d4f0cf1252cc55dbee8691',
    messagingSenderId: '816730900420',
    projectId: 'realtime-chat-63922',
    authDomain: 'realtime-chat-63922.firebaseapp.com',
    storageBucket: 'realtime-chat-63922.appspot.com',
    measurementId: 'G-87QSJD0P3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABSU-1gzwYSKgI1r1Gxc4wc86RCscdshE',
    appId: '1:816730900420:android:d432602dc6aa0dd3ee8691',
    messagingSenderId: '816730900420',
    projectId: 'realtime-chat-63922',
    storageBucket: 'realtime-chat-63922.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW1VtLdktAXvtrbcXfqXZjYR-ZTsuYaWo',
    appId: '1:816730900420:ios:dc5f8e4d4a6e3ef1ee8691',
    messagingSenderId: '816730900420',
    projectId: 'realtime-chat-63922',
    storageBucket: 'realtime-chat-63922.appspot.com',
    iosClientId: '816730900420-v8pa845a94lieloonv1ji4pls04mid8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.realtimeChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW1VtLdktAXvtrbcXfqXZjYR-ZTsuYaWo',
    appId: '1:816730900420:ios:dc5f8e4d4a6e3ef1ee8691',
    messagingSenderId: '816730900420',
    projectId: 'realtime-chat-63922',
    storageBucket: 'realtime-chat-63922.appspot.com',
    iosClientId: '816730900420-v8pa845a94lieloonv1ji4pls04mid8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.realtimeChat',
  );
}
